# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# S? d?ng Built-in Kotlin c?a AGP 9.0
android.builtInKotlin=true
# Cho phép KSP s? d?ng c?u trúc sourceSets c? ?? tránh l?i trên AGP 9.x
android.disallowKotlinSourceSets=false
